import { Test, TestingModule } from '@nestjs/testing';
import { ReportStatus } from '@/common/enums/report-status.enum';
import { ReportsRepository } from '../repositories/reports.repository';
import { ReportsQueryDto, SortBy, SortOrder } from '../dto/reports-query.dto';
import { ReportsService } from './reports.service';

describe('ReportsService', () => {
  let service: ReportsService;
  let repository: ReportsRepository;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [ReportsService, ReportsRepository],
    }).compile();

    service = module.get<ReportsService>(ReportsService);
    repository = module.get<ReportsRepository>(ReportsRepository);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('listReports', () => {
    it('returns the paging shape generated by Orval', () => {
      const result = service.listReports({ page: 0, pageSize: 10 });

      expect(result.paging.totalElements).toBe(200);
      expect(result.paging.totalPages).toBe(20);
      expect(result.paging.page).toBe(0);
      expect(result.paging.elementsPerPage).toBe(10);
      expect(result.response).toHaveLength(10);
    });

    it('returns an empty response when the page is beyond the total', () => {
      const result = service.listReports({ page: 999, pageSize: 10 });

      expect(result.response).toHaveLength(0);
      expect(result.paging.totalPages).toBe(20);
    });

    it('filters by status using the API enum values', () => {
      const result = service.listReports({
        page: 0,
        pageSize: 100,
        status: [ReportStatus.SENT, ReportStatus.READY_TO_SEND],
      });

      result.response.forEach((record) => {
        expect([ReportStatus.SENT, ReportStatus.READY_TO_SEND]).toContain(
          record.reportStatus,
        );
      });
    });

    it('filters by search using codeUc and nickname', () => {
      const firstReport = repository.findAll()[0];
      const result = service.listReports({
        page: 0,
        pageSize: 100,
        search: firstReport.uc.slice(0, 5).toLowerCase(),
      });

      expect(result.response.length).toBeGreaterThan(0);
      result.response.forEach((record) => {
        expect(record.codeUc?.toLowerCase()).toContain('uc-');
      });
    });

    it('filters by startDate and endDate using the contract format', () => {
      const result = service.listReports({
        page: 0,
        pageSize: 100,
        startDate: '2026-02-01',
        endDate: '2026-02-28',
      });

      result.response.forEach((record) => {
        expect(record.referenceDate).toBe('2026-02-01');
      });
    });

    it('filters by economicGroup as an array', () => {
      const result = service.listReports({
        page: 0,
        pageSize: 100,
        economicGroup: ['grupo econômico a'],
      });

      expect(result.response.length).toBeGreaterThan(0);
      result.response.forEach((record) => {
        expect(record.economicGroup?.toLowerCase()).toContain('grupo econômico a');
      });
    });

    it('sorts by nickname ascending using order and orderBy', () => {
      const result = service.listReports({
        page: 0,
        pageSize: 10,
        orderBy: SortBy.NICKNAME,
        order: SortOrder.ASC,
      });

      for (let i = 1; i < result.response.length; i++) {
        expect(
          (result.response[i].nickname ?? '').localeCompare(
            result.response[i - 1].nickname ?? '',
          ),
        ).toBeGreaterThanOrEqual(0);
      }
    });

    it('returns records in the remote API shape', () => {
      const result = service.listReports({ page: 0, pageSize: 1 });
      const record = result.response[0];

      expect(record).toHaveProperty('correlationId');
      expect(record).toHaveProperty('codeUc');
      expect(record).toHaveProperty('nickname');
      expect(record).toHaveProperty('referenceDate');
      expect(record).toHaveProperty('economicGroup');
      expect(record).toHaveProperty('reportStatus');
      expect(record).toHaveProperty('message');
      expect(record.referenceDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });
  });

  describe('summary', () => {
    it('returns totalReports in addition to the counters', () => {
      const result = service.getSummary('2026-02-01');

      expect(result).toHaveProperty('totalReports');
      expect(result).toHaveProperty('sentReportsPercentage');
      expect(result).toHaveProperty('reportsToGenerate');
      expect(result).toHaveProperty('reportsPendingCorrection');
      expect(result).toHaveProperty('reportsReadyToSend');
      expect(result).toHaveProperty('reportsSent');
    });

    it('counts pending correction using the aligned enum names', () => {
      const allReports = repository.findAll();
      const expectedCount = allReports.filter(
        (r) =>
          r.status === ReportStatus.PENDING_INFORMATION ||
          r.status === ReportStatus.NEED_ANALYSIS,
      ).length;

      expect(service.getResume().reportsPendingCorrection).toBe(expectedCount);
    });
  });

  describe('generate', () => {
    it('returns the generate response shape for bulk generation', () => {
      const result = service.generate('2026-02-01');

      expect(result.correlationId).toContain('mock-2026-02-01');
      expect(result.message).toBe('Reports sent to queue');
    });

    it('returns the generate response shape for a correlationId', () => {
      const result = service.generate('2026-02-01', 'corr-123');

      expect(result.correlationId).toBe('corr-123');
      expect(result.message).toBe('Report sent to queue');
    });
  });
});
