export enum ReportStatus {
  READY_TO_GENERATE = 'READY_TO_GENERATE',
  GENERATING_REPORT = 'GENERATING_REPORT',
  PENDING_INFORMATION = 'PENDING_INFORMATION',
  NEED_ANALYSIS = 'NEED_ANALYSIS',
  PROCESSING_ERROR = 'PROCESSING_ERROR',
  READY_TO_SEND = 'READY_TO_SEND',
  QUEUED_FOR_SENDING = 'QUEUED_FOR_SENDING',
  SENT = 'SENT',
  SENDING_ERROR = 'SENDING_ERROR',
}
